#Datapool details

databookUI=UIData

#Authentication and Authorization
loginUser=raj
password=raj123

#Test Properties
reportPath=src/test/resources/SourcePdfs
imagePath=src/test/resources/ConvertedImages

browser=Chrome

